### ISSUE TITLE
Kill Screen Score Broken

### ISSUE THREAD

**Issue by Chirishman** [TEAMarg/ID-30-BEGEMMED#2]
Game over screen score is always 000000 on all difficulties. Loaded the Arduboy version using the latest Arduboy GameLoader (beta 21)

**Comment by JO3RI** [comment]
I'll look into this when back from vacation in August :)

**Comment by Chirishman** [comment]
@JO3RI Any luck reproducing/fixing this?

**Comment by Chirishman** [comment]
Patched in dba32e973704aaa19d12607911a37ef105323325
